
server:
  port: 8080


spring:
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/virspit_auth?allowMultiQueries=true&useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&passwordCharacterEncoding=UTF-8
    username: root
    password: password


  logging:
    level:
      org.hibernate:
        SQL: DEBUG # to logger
        type.descriptor.sql.BasicBinder: DEBUG
      org.springframework.jdbc.core:
        JdbcTemplate: DEBUG
        StatementCreatorUtils: DEBUG


security:
  jwt:
    token:
      security-key: secret-key

      expiration-length: 3600000


UserController:
  signup: Creates user and returns its JWT token
  signin: Authenticates user and returns its JWT token
